/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/dancer.glb --types --output src/components/Dancer.tsx 
Author: The Smithsonian Institution (https://sketchfab.com/Smithsonian)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/figure-of-a-dancer-63212acff8474095ba2626d9366df852
Title: Figure of a Dancer
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { StatueColor } from "../../types/colors";


type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
  };
  materials: {
    ["default"]: THREE.MeshStandardMaterial;
  };
};

type DancerProps = {
  color?: StatueColor
} & React.ComponentProps<'group'>

export function Dancer({color, ...props}: DancerProps) {
  const { nodes } = useGLTF(
    "/models/dancer.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} castShadow receiveShadow>
            <meshStandardMaterial
              color={color?.primary || "#FFD700"}
              roughness={0.4}
              metalness={0.6}
            />
          </mesh>

          <mesh geometry={nodes.Object_5.geometry} castShadow receiveShadow>
            <meshStandardMaterial
              color={color?.secondary || "#FFF"}
              roughness={0.3}
              metalness={0.1}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/dancer.glb");
