/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stage.glb --types --output src/components/Stage.tsx 
Author: local.yany (https://sketchfab.com/local.yany)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stage-57b58ad84f0e43a8986e567d72413345
Title: Stage
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { StatueColor } from "../../types/colors";

type GLTFResult = GLTF & {
  nodes: {
    Stage_BaseShape_StageBasa_trim_0: THREE.Mesh;
    Stage_BaseShape_StageBase_0: THREE.Mesh;
  };
  materials: {
    StageBasa_trim: THREE.MeshStandardMaterial;
    StageBase: THREE.MeshStandardMaterial;
  };
};

type StageProps = {
  color?: StatueColor;
} & React.ComponentProps<"group">;

export function Stage({ color, ...props }: StageProps) {
  const { nodes } = useGLTF("/models/stage.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Stage_BaseShape_StageBasa_trim_0.geometry}
          castShadow
          receiveShadow
        >
          <meshStandardMaterial
            color={color?.primary || "#FFFFFF"}
            roughness={0.4}
            metalness={0.5}
          />
        </mesh>

        <mesh
          geometry={nodes.Stage_BaseShape_StageBase_0.geometry}
          castShadow
          receiveShadow
        >
          <meshStandardMaterial
            color={color?.secondary || "#FFFFFF"}
            roughness={0.1}
            metalness={0.1}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/stage.glb");
